config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  get 'restaurants/index', as: 'user_root'
    resources :restaurants do
      member do
        patch 'confirm'
      end
      collection do
        post 'confirm'
      end
    end

  resources :reviews, only: [:create, :destroy]
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    has_many :restaurant_genres
    has_many :genres, through: :restaurant_genres
    has_many :restaurant_images, dependent: :destroy
    has_many :reviews, dependent: :destroy
    accepts_nested_attributes_for :restaurant_images
    
    geocoded_by :address
    after_validation :geocode
    
    validates :name, presence: true
    validates :user_id, presence: true
    validates :restaurant_genres, length: { minimum: 1}
    validates :telephone_number, presence: true
    validates :address, presence: true
    validates :introduction, presence: true
    validates :has_private_room, inclusion: {in: [true, false]} 
    validates :seat_count, presence: true, numericality: true
    validates_numericality_of :seat_count, greater_than: 0
    validates :open_date, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @q = Restaurant.search(params[:q])
    @restaurants = @q.result.page(params[:page]).per(20).order(:id)
  end
  
  def show
    @restaurant = Restaurant.find(params[:id])
    @map = Gmaps4rails.build_markers([@restaurant]) do |res, marker|
      marker.lat res.latitude
      marker.lng res.longitude
      marker.json({title: res.name})
    end
    if user_signed_in?
      if @restaurant.reviews.select{|s| s.user_id == current_user.id}.length == 0
        @review = Review.new
      end
    end
  end
  
  def new
    @restaurant = Restaurant.new
    5.times do
      @restaurant.restaurant_images.build
    end
  end
  
  def confirm
    if params[:id].present?
      @restaurant = Restaurant.find(params[:id])
      @restaurant.attributes = input_params
      @restaurant.user_id = current_user.id
      if @restaurant.invalid?
        flash.now[:alert] = @restaurant.errors.full_messages
        render :edit
      elsif !@restaurant.restaurant_images.first.image?
        @restaurant.errors[:base] << I18n.t('restaurant.image_error')
        flash.now[:alert] = @restaurant.errors.full_messages
        render :edit
      end
    else
      @restaurant = Restaurant.new(input_params)
      @restaurant.user_id = current_user.id
      if @restaurant.invalid?
        flash.now[:alert] = @restaurant.errors.full_messages
        render :new
      elsif !@restaurant.restaurant_images.first.image?
        @restaurant.errors[:base] << I18n.t('restaurant.image_error')
        flash.now[:alert] = @restaurant.errors.full_messages
        render :new
      end
    end
    @map = Gmaps4rails.build_markers([@restaurant]) do |res, marker|
      marker.lat res.latitude
      marker.lng res.longitude
      marker.json({title: res.name})
    end
  end
  
  
  
  def create
    @restaurant = Restaurant.new(input_params)
    @restaurant.user_id = current_user.id
    if params[:back]
      render :new
    else
      @restaurant.save!
      flash[:notice] = I18n.t('restaurant.created')
      redirect_to action: :index
    end
  end
  
  def edit
    @restaurant = Restaurant.find_by(id: params[:id], user_id: current_user.id)
  end
  
  def update
    @restaurant = Restaurant.find_by(id: params[:id], user_id: current_user.id)
    @restaurant.attributes = input_params
    if params[:back]
      render :edit
    else
      @restaurant.save!
      flash[:notice] = I18n.t('restaurant.updated')
      redirect_to action: :show, id: @restaurant.id
    end
  end
  
  def destroy
    restaurant = Restaurant.find_by(id: params[:id], user_id: current_user.id)
    restaurant.destroy!
    flash[:notice] = I18n.t('restaurant.deleted')
    redirect_to action: :index  
  end
  
  private
  def input_params
    params.require(:restaurant).permit(:name, :telephone_number, :address, :introduction, :has_private_room, :seat_count, :open_date, genre_ids: [], restaurant_images_attributes: [:id, :image, :image_cache])
  end
  
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
    def genre_name_list(genres)
      genres.map(&:name)
    end
end

app/views/restaurants/_genre_list.html.erb
<ul class="genre_list">
  <% genre_name_list(restaurant.genres).each do |g| %>
    <li><%= g %></li>
  <% end %>
</ul>

app/views/restaurants/_input.html.erb
<div class="wrapper restaurant_input">
  <div class="header">
    <%= link_to 'レストラン一覧に戻る', root_path %>
  </div>

  <hr>

  <h3>レストラン登録</h3>

  <%= form_for @restaurant, url: {action: 'confirm'} do |f| %>
    
    <div class="alert">
      <% if flash[:alert] %>
        <% flash[:alert].each do |message| %>
          <p class="alert"><%= message %></p>
        <% end %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br/>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :introduction %><br/>
      <%= f.cktext_area :introduction, rows: 3, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :telephone_number %><br/>
      <%= f.text_field :telephone_number, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :address %><br/>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :genre_ids %><br/>
      <% Genre.all.order(:id).each do |g| %>
        <label class="checkbox-inline">
          <%= f.check_box :genre_ids, { multiple: true, include_hidden: false, checked: @restaurant.genre_ids.include?(g.id)}, g.id, nil %>
          <%= g.name %>
        </label>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :has_private_room %><br/>
      <%= f.radio_button :has_private_room, true %>有
      <%= f.radio_button :has_private_room, false %>無
    </div>

    <div class="form-group">
      <%= f.label :seat_count %><br/>
      <%= f.number_field :seat_count, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :open_date %><br/>
      <%= f.date_field :open_date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag I18n.t('activerecord.attributes.restaurant.image') %><br/>
      <%= f.fields_for :restaurant_images do |rf| %>
        <%= rf.file_field :image %> <%= "設定中[#{rf.object.image}]" if rf.object.image? %>
        <%= rf.hidden_field :image_cache %>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit "確認", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/restaurants/_per_restaurant.html.erb
<%= link_to restaurant_path(restaurant) do %>
    <div class="per_restaurant">
      <div class="name">
        <%= restaurant.name %>
      </div>
      <div class="content clearfix">
        <div class="image">
          <% if restaurant.restaurant_images.first.image? %>
            <%= image_tag restaurant.restaurant_images.first.image.url %>
          <% end %>
        </div>
        <div>
          <div class="genres">
            <%= render 'restaurants/genre_list', restaurant: restaurant %>
          </div>
        </div>
        <div class="introduction">
            <!--<p><%= raw restaurant.introduction %></p>-->
            <p><%= strip_tags(restaurant.introduction) %></p>
        </div>
      </div>
    </div>
<% end %>

app/views/restaurants/confirm.html.erb
<div class="wrapper restaurant_confirm">
  <h3>レストラン登録確認</h3>

  <%= form_for @restaurant do |f| %>
    <table class="table">
      <tr>
        <th style="width:100px"><%= f.label :name %></th>
        <td><%= @restaurant.name %></td>
        <%= f.hidden_field :name %>
      </tr>
      <tr>
        <th><%= label :restaurant, :introduction %></th>
        <td><%= raw @restaurant.introduction %></td>
        <%= f.hidden_field :introduction %>
      </tr>
      <tr>
        <th><%= f.label :telephone_number %></th>
        <td><%= @restaurant.telephone_number %></td>
        <%= f.hidden_field :telephone_number %>
      </tr>
      <tr>
        <th><%= f.label :address %></th>
        <td>
          <%= @restaurant.address %>
          <div style='width: 350px;'>
            <div id="map" style='width: 350px; height: 350px;'></div>
          </div>
        </td>
        <%= f.hidden_field :address %>
      </tr>
      <tr>
        <th><%= f.label :genre_ids %></th>
        <td>
          <%= render 'restaurants/genre_list', restaurant: @restaurant %>
        </td>
        <% @restaurant.genre_ids.each do |r| %>
           <%= f.hidden_field :genre_ids, multiple: true, value: r %>
        <% end %>
      </tr>
      <tr>
        <th><%= f.label :has_private_room %></th>
        <td><%= @restaurant.has_private_room ? '有' : '無' %></td>
        <%= f.hidden_field :has_private_room %>
      </tr>
      <tr>
        <th><%= f.label :seat_count %></th>
        <td><%= @restaurant.seat_count %></td>
        <%= f.hidden_field :seat_count %>
      </tr>
      <tr>
        <th><%= f.label :open_date %></th>
        <td><%= @restaurant.open_date %></td>
        <%= f.hidden_field :open_date %>
      </tr>

      <%= f.fields_for :restaurant_images do |rf| %>
        <% if rf.object.image? %>
          <tr class="image">
            <th><%= f.label :image %></th>
            <td><%= image_tag rf.object.image.url %></td>
          </tr>
        <% end %>
        <%= rf.hidden_field :image %>
        <%= rf.hidden_field :image_cache %>
      <% end %>

    </table>

    <div class="actions">
      <%= f.submit "戻る", class: 'btn btn-danger', name: 'back' %>
      <%= f.submit "登録", class: 'btn btn-primary' %>
    </div>

  <% end %>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @map.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/restaurants/edit.html.erb
<%= render 'restaurants/input' %>

app/views/restaurants/index.html.erb
<div class="wrapper restaurant_index">
  <div class="new_restaurant">
    <%= button_to 'レストラン追加', new_restaurant_path, method: :get, class: 'btn btn-primary' %>
  </div>
  
  <div class="clearfix">
      <div class="col-md-4">
          <div class="search_wrapper">
              <%= search_form_for @q , url: user_root_path do |f| %>
                <ul class="list-group">
                  <li class="list-group-item">
                      <%= f.label :name %> <%= f.text_field :name_cont%>
                  </li>
                  <li class="list-group-item">
                      <%= f.label :seat_count %><br/>
                      <%= f.text_field :seat_count_gteq %>~<%= f.text_field :seat_count_lteq %>
                  </li>
                  <li class="list-group-item">
                      <%= f.label :has_private_room %><br/>
                      <%= f.radio_button :has_private_room_eq, true %>有<br/>
                      <%= f.radio_button :has_private_room_eq, false %>無
                  </li>
                  <li class="list-group-item">
                      <%= f.label :open_date %><br/>
                      <%= f.date_field :open_date_gteq %>~<%= f.date_field :open_date_lteq %>
                  </li>
                  <li class="list-group-item">
                      <%= f.submit '検索', class: 'btn btn-primary' %>
                      <%= link_to 'クリア', request.path, class: 'btn btn-default' %>
                  </li>
                </ul>
            <% end %>
          </div>
      </div>
      <div class="col-md-8">
          <div class="restaurant_list_count">
            <%= @restaurants.length == 0 ? 0 : @restaurants.offset_value + 1 %> 〜 <%= @restaurants.offset_value + @restaurants.length %> 件目を表示 / 全<%= @restaurants.total_count %>件            
          </div>
          <div class="restaurant_list">
            <% @restaurants.each do |restaurant| %>
              <%= render 'restaurants/per_restaurant', restaurant: restaurant %>
            <% end %>
          </div>
          <div>
              <%= paginate @restaurants %>
          </div>
      </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render 'restaurants/input' %>

app/views/restaurants/show.html.erb
<div class="wrapper restaurant_show">
    <div class="header">
        <%= link_to 'レストラン一覧に戻る', root_path %>
    </div>
    
    <hr>
    <div class="clearfix">
        <div class="name">
            <%= @restaurant.name %>
        </div>
        
        <% if user_signed_in? && @restaurant.user_id == current_user.id %>
          <div class="operation_restaurant">
            <%= link_to '編集', edit_restaurant_path, class: 'btn btn-primary' %>
            <%= link_to '削除', restaurant_path, method: :delete, class: 'btn btn-danger', data: {confirm: '削除してもよろしいですか？'} %>
          </div>
        <% end %>
    </div>
    
    <div class="clearfix">
        <div class="col-md-5">
            <div class="big-image">
                <%= image_tag @restaurant.restaurant_images.first.image.url, id: 'big_image' %>
            </div>
            <ul class="small_images">
                <% @restaurant.restaurant_images.each do |ri| %>
                  <% if ri.image? %>
                    <li>
                        <%= image_tag ri.image.url %>
                    </li>
                  <% end %>
                <% end %>
            </ul>
        </div>
        <div class="col-md-7 info">
            <div>
                <%= label :restaurant, :introduction %> <br/>
                <%= raw @restaurant.introduction %>
            </div>
            <div>
                <%= label :restaurant, :telephone_number %><%= @restaurant.telephone_number %>
            </div>
            <div>
                <%= label :restaurant, :address %><%= @restaurant.address %>
                <div style='width: 100%; '>
                    <div id="map" style='width: 100%; height: 350px;'></div>
                </div>
            </div>
            <div>
                <%=label :restaurant, :genre_ids %><br/>
                <%= render 'restaurants/genre_list', restaurant: @restaurant %>
            </div>
            <div>
                <%= label :restaurant, :has_private_room %><%= @restaurant.has_private_room ? '有' : '無' %>
            </div>
            <div>
                <%= label :restaurant, :seat_count %><%= @restaurant.seat_count %>席
            </div>
            <div>
                <%= label :restaurant, :open_date %><%= @restaurant.open_date %>
            </div>
        </div>
    </div>
    <% if user_signed_in? %>
      <div class="my_review_wrapper">
          <% if @review %>
            <%= form_for @review do |f| %>
              <%= f.cktext_area :body, rows: 3, placeholder:'レビューを書く' %>
              <div class="footer_menu clearfix">
                  <div class="rank">
                      <%= f.label :rank %>  <%= f.select :rank, 5.downto(1).map {|m| [m,m]}, {}, class: 'form-control' %>
                  </div>
                  <div class="review_post">
                      <%= f. submit 'レビュー', class: 'btn btn-primary' %>
                  </div>
                </div>
                  <%= f.hidden_field :restaurant_id, value: @restaurant.id %>
              <% end %>
          <% else %>
            <p>レビュー済みです</p>
          <% end %>
      </div>
    <% end %>
    
    <hr>
    
    <div class="review_list_wrapper">
        レビュー数<%= @restaurant.reviews.length %>
        
        <div class="review_list">
            <% @restaurant.reviews.each do |review| %>
              <%= render 'reviews/per_review', review: review %>
            <% end %>
        </div>
    </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @map.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>