config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  get 'restaurants/index', as: 'user_root'
    resources :restaurants do
      member do
        patch 'confirm'
      end
      collection do
        post 'confirm'
      end
    end

  resources :reviews, only: [:create, :destroy]
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        review = Review.new
        review.attributes = input_params
        review.user_id = current_user.id
        if review.valid?
            review.save!
            flash[:notice] = I18n.t('review.created')
            redirect_to restaurant_path(review.restaurant_id)
        else
            flash[:alert] = review.errors.full_messages
            redirect_to request.referer
        end
    end
    
    def destroy
        review = Review.find(params[:id])
        restaurant_id = review.restaurant_id
        review.destroy!
        flash[:notice] = I18n.t('review.deleted')
        redirect_to restaurant_path(restaurant_id)
    end
    
    private
    
    def input_params
      params.require(:review).permit(:restaurant_id, :rank, :body)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_per_review.html.erb
<div class="review clearfix">
    <div class="thumbnail">
        <% if review.user.thumbnail? %>
          <%= image_tag review.user.thumbnail.url %>
        <% else %>
          <div class="no _thumbnail"></div>
        <% end %>
    </div>
    <div class="review_contents">
        <div class="review_header clearfix">
            <%= review.user.name %>
            <div class="rank">
              <%= '★' * review.rank %><%= '☆' * (5 - review.rank) %>
            </div>
            <% if user_signed_in? && review.user.id == current_user.id %>
              <div class="delete">
                 <%= button_to '削除', review_path(review.id) , method: :delete, class: 'btn btn-danger' , data: {confirm: '削除してもよろしいですか？'} %> 
              </div>
            <% end %>
        </div>
        <div class="review_body">
            <%= raw review.body %>
        </div>
    </div>
</div>